## Importing the Numpy Module

In [1]:
import numpy as np

## Creating the Array using numpy

In [2]:

arra=np.array([[1,2,3],[4,5,6]])


In [3]:
print(arra)

[[1 2 3]
 [4 5 6]]


In [4]:
arra.ndim

2

In [5]:
arra.shape

(2, 3)

In [6]:
arra.dtype

dtype('int32')

In [7]:
arra[1,1]=34

In [8]:
arra

array([[ 1,  2,  3],
       [ 4, 34,  6]])

## Creating Complex Array

In [9]:
arr=np.array([[1,2,3],[4,5,6]],dtype=complex)

In [10]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [11]:
arra.itemsize

4

## Reshape the array

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [13]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [14]:
ar=arr.reshape((3,3))

## Slicing the array

In [15]:
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(ar[1,1])

5


## Lin_space

In [17]:
arr=np.linspace(100,200,10)

In [18]:
print(arr)

[100.         111.11111111 122.22222222 133.33333333 144.44444444
 155.55555556 166.66666667 177.77777778 188.88888889 200.        ]


In [19]:
arr.max()

200.0

In [20]:
arr.min()

100.0

In [21]:
arr.sum()

1500.0

In [22]:
arr=np.zeros((3,3),dtype=int)

In [23]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## interating the numpy array

In [25]:
for i in np.nditer(ar):
    print(i)

1
2
3
4
5
6
7
8
9


In [26]:
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
np.around(arr,2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.around(arr,0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.around(arr,-1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
import numpy

def arrays(arr):
    ls=[]
    for i in reversed(arr):
        ls.append(i)
    arr=numpy.array(ls,float)
    return arr
    
    
arr = input().strip().split(' ')
result=arrays(arr)
print(result)

In [ ]:
import numpy as np

arr=input().split(" ")
new_array=np.array(arr,int)
reshaped_array=new_array.reshape((3,3))
print(reshaped_array)

In [ ]:
import numpy as np

n,m=map(int,input().split(" "))
lst=[]
for i in range(n):
    a=input().split()
    lst.append(a)
new_array=np.array(lst,int)
print(new_array.T)
print(new_array.flatten())


In [ ]:
import numpy as np
n,m,p=map(int,input().split(" "))
lst1=[]
lst2=[]
for i in range(n):
    a,b=input().split(" ")
    lst1.append([int(a),int(b)])
for i in range(m):
    a,b=input().split(" ")
    lst2.append([int(a),int(b)])
arr1=np.array(lst1)
arr2=np.array(lst2)
array=np.concatenate((arr1,arr2))
print(array)

In [ ]:
import numpy as np
a,b,c=map(int,input().split(" "))
arr1=np.zeros((a,b),dtype=int)
arr2=np.ones((a,b),dtype=int)
z=[]
o=[]
for i in range(c):
    z.append(arr1)
    o.append(arr2)
array_of_zeros=np.array(z)
array_of_ones=np.array(o)
print(array_of_zeros,array_of_ones,sep="\n")

# for i in range(c):
#     print(z[i])
# for i in range(c):
#     print(o[i])

## Random Module in Numpy

In [31]:
import numpy as np
var=np.random.randn(12)
var

array([-0.00838043,  0.12753693, -0.43907418,  0.07517184, -1.83537959,
       -0.02471498,  0.03013122, -0.15282722,  1.35940801,  0.34385396,
        1.33491521,  0.71562998])

In [33]:
var=np.random.randn(2,3)
var

array([[-0.08536137,  0.9609909 ,  0.39653428],
       [ 0.65170463, -0.87137259,  0.70144508]])

In [34]:
type(var)

numpy.ndarray

In [35]:
var.shape

(2, 3)

In [36]:
var.size

6

In [37]:
var.ndim

2

In [40]:
for i in var.flat:
    print(int(i))

0
0
0
0
0
0


In [42]:
var=np.random.randint(2,20,10)
var

array([ 7, 15, 12, 14,  4, 14,  7, 10, 16, 19])

In [44]:
print(var.sort())

None


In [45]:
var.sort

<function ndarray.sort>

In [46]:
np.sort(var)

array([ 4,  7,  7, 10, 12, 14, 14, 15, 16, 19])

## Joining the 2 Arrays

In [60]:
array1=np.array([[1,2,3,4],[7,8,9]])
array2=np.array([5,6,7,8])
arr=np.concatenate((array1,array2))
arr

C:\Users\asus\AppData\Local\Temp\ipykernel_9004\3294047967.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1=np.array([[1,2,3,4],[7,8,9]])


array([list([1, 2, 3, 4]), list([7, 8, 9]), 5, 6, 7, 8], dtype=object)

## inserting and deletion

In [61]:
array1

array([list([1, 2, 3, 4]), list([7, 8, 9])], dtype=object)

In [65]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.insert(arr,2,3)

array([1, 2, 3, 3, 4, 5, 6])

In [77]:
np.delete(arr,5)

array([1, 2, 3, 4, 5])

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

## matrix in Numpy

In [78]:
import numpy as np

In [79]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### It's not recommended to use the matrix class as it will be removed from the future
source : numpy original docs says
###### so we will be using the arrays only  to demonstrate the matrix

## Linear Algebra using Numpy

In [81]:
arr=np.array([[1,2,3],[4,5,6]])

In [82]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2=np.array([[11,22,33],[44,55,66]])

In [85]:
arr2

array([[11, 22, 33],
       [44, 55, 66]])

In [91]:
np.dot(arr[0],arr[1])

32

In [90]:
arr[0]

array([1, 2, 3])

In [93]:
np.linalg.det(arr)

LinAlgError: Last 2 dimensions of the array must be square